//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen2OscarMorales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaCAsa
    {
        public long idVenta { get; set; }
        public string DescripcionCasa { get; set; }
        public Nullable<decimal> PrecioCasa { get; set; }
        public string Vendedor { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
    }
}
